import { Language } from './types';
import { TRANSLATIONS } from './translations';

export function resolveUiLang(lang: Language): Language {
  return lang === 'en-US' ? 'en' : lang;
}

export function isRtlLang(lang: Language | string): boolean {
  return lang === 'fa' || lang === 'ar';
}

const UI_STRINGS: Record<string, Record<string, string>> = {
  fa: {
    uiLanguageLabel: 'زبان برنامه',
    uiLanguageHint: 'فقط دکمه‌ها و متن راهنما. روی کارت‌ها اثر ندارد.',
    nativeLanguageHint: 'معنی کارت به این زبان دیده می‌شود.',
    nextTopics: 'مرحله بعد (موضوعات)',
    nextSetup: 'مرحله بعد (تنظیمات)',
    nextPlayers: 'مرحله بعد (بازیکنان)',
    stepOf: 'مرحله {n} از {total}',
    stepLanguages: 'زبان‌ها و سطح',
    stepTopics: 'موضوعات',
    stepSetup: 'تنظیمات مسابقه',
    stepPlayers: 'نام بازیکنان',
    tapMascot: 'بزن رو من شاد شی!',
    onlineMultiplayer: 'بازی آنلاین (دیسکورد / میت)',
    installApp: 'نصب روی موبایل',
    installSub: 'افزودن به صفحه اصلی • آفلاین',
    addToHome: 'نصب / افزودن',
    comingSoonStores: 'نسخه اندروید و iOS به‌زودی در استورها',
    essentialsTopics: 'موضوعات ضروری',
    activeCount: '{n} زبان',
    hearPhrase: 'بشنو',
  },
  en: {
    uiLanguageLabel: 'App language',
    uiLanguageHint: 'Buttons and help only. Card languages stay separate.',
    nativeLanguageHint: 'Card meanings appear in this language.',
    nextTopics: 'Next (topics)',
    nextSetup: 'Next (setup)',
    nextPlayers: 'Next (players)',
    stepOf: 'Step {n} of {total}',
    stepLanguages: 'Languages & level',
    stepTopics: 'Topics',
    stepSetup: 'Match settings',
    stepPlayers: 'Player names',
    tapMascot: 'Ready to Party! Tap Me!',
    onlineMultiplayer: 'Online multiplayer (Discord / Meet)',
    installApp: 'Install on phone',
    installSub: 'Add to Home Screen • Works offline',
    addToHome: 'Install / Add',
    comingSoonStores: 'Android & iOS store apps coming soon',
    essentialsTopics: 'Essentials',
    activeCount: '{n} languages',
    hearPhrase: 'Listen',
  },
  nl: {
    uiLanguageLabel: 'App-taal',
    uiLanguageHint: 'Alleen knoppen en hulp. Kaarttalen blijven apart.',
    nativeLanguageHint: 'Betekenis van kaarten in deze taal.',
    nextTopics: 'Volgende (onderwerpen)',
    nextSetup: 'Volgende (instellingen)',
    nextPlayers: 'Volgende (spelers)',
    stepOf: 'Stap {n} van {total}',
    stepLanguages: 'Talen & niveau',
    stepTopics: 'Onderwerpen',
    stepSetup: 'Wedstrijdinstellingen',
    stepPlayers: 'Spelersnamen',
    tapMascot: 'Klaar voor feest! Tik me!',
    onlineMultiplayer: 'Online (Discord / Meet)',
    installApp: 'Installeer op je telefoon',
    installSub: 'Op beginscherm • Offline',
    addToHome: 'Installeren',
    comingSoonStores: 'Android- en iOS-apps komen eraan',
    essentialsTopics: 'Essentieel',
    activeCount: '{n} talen',
    hearPhrase: 'Luister',
  },
  de: {
    uiLanguageLabel: 'App-Sprache',
    uiLanguageHint: 'Nur Tasten und Hilfe. Karten bleiben getrennt.',
    nativeLanguageHint: 'Kartenbedeutung in dieser Sprache.',
    nextTopics: 'Weiter (Themen)',
    nextSetup: 'Weiter (Einstellungen)',
    nextPlayers: 'Weiter (Spieler)',
    stepOf: 'Schritt {n} von {total}',
    stepLanguages: 'Sprachen & Niveau',
    stepTopics: 'Themen',
    stepSetup: 'Spieleinstellungen',
    stepPlayers: 'Spielernamen',
    tapMascot: 'Party ready! Tippe mich!',
    onlineMultiplayer: 'Online (Discord / Meet)',
    installApp: 'Aufs Handy installieren',
    installSub: 'Zum Startbildschirm • Offline',
    addToHome: 'Installieren',
    comingSoonStores: 'Android- und iOS-Apps folgen',
    essentialsTopics: 'Wichtigste',
    activeCount: '{n} Sprachen',
    hearPhrase: 'Hören',
  },
  fr: {
    uiLanguageLabel: 'Langue de l’app',
    uiLanguageHint: 'Boutons et aide seulement. Les cartes restent séparées.',
    nativeLanguageHint: 'Le sens des cartes s’affiche dans cette langue.',
    nextTopics: 'Suivant (thèmes)',
    nextSetup: 'Suivant (réglages)',
    nextPlayers: 'Suivant (joueurs)',
    stepOf: 'Étape {n} sur {total}',
    stepLanguages: 'Langues et niveau',
    stepTopics: 'Thèmes',
    stepSetup: 'Réglages',
    stepPlayers: 'Noms des joueurs',
    tapMascot: 'Prêt à faire la fête !',
    onlineMultiplayer: 'En ligne (Discord / Meet)',
    installApp: 'Installer sur le téléphone',
    installSub: 'Écran d’accueil • Hors ligne',
    addToHome: 'Installer',
    comingSoonStores: 'Apps Android et iOS bientôt',
    essentialsTopics: 'Essentiels',
    activeCount: '{n} langues',
    hearPhrase: 'Écouter',
  },
  es: {
    uiLanguageLabel: 'Idioma de la app',
    uiLanguageHint: 'Solo botones y ayuda. Las cartas van aparte.',
    nativeLanguageHint: 'El significado de la carta sale en este idioma.',
    nextTopics: 'Siguiente (temas)',
    nextSetup: 'Siguiente (ajustes)',
    nextPlayers: 'Siguiente (jugadores)',
    stepOf: 'Paso {n} de {total}',
    stepLanguages: 'Idiomas y nivel',
    stepTopics: 'Temas',
    stepSetup: 'Ajustes',
    stepPlayers: 'Nombres',
    tapMascot: '¡A la fiesta! Tócame',
    onlineMultiplayer: 'En línea (Discord / Meet)',
    installApp: 'Instalar en el móvil',
    installSub: 'Pantalla de inicio • Sin red',
    addToHome: 'Instalar',
    comingSoonStores: 'Apps de Android e iOS pronto',
    essentialsTopics: 'Esenciales',
    activeCount: '{n} idiomas',
    hearPhrase: 'Escuchar',
  },
  it: {
    uiLanguageLabel: 'Lingua dell’app',
    uiLanguageHint: 'Solo pulsanti e guida. Le carte restano separate.',
    nativeLanguageHint: 'Il significato della carta è in questa lingua.',
    nextTopics: 'Avanti (argomenti)',
    nextSetup: 'Avanti (impostazioni)',
    nextPlayers: 'Avanti (giocatori)',
    stepOf: 'Passo {n} di {total}',
    stepLanguages: 'Lingue e livello',
    stepTopics: 'Argomenti',
    stepSetup: 'Impostazioni',
    stepPlayers: 'Nomi',
    tapMascot: 'Pronto per la festa!',
    onlineMultiplayer: 'Online (Discord / Meet)',
    installApp: 'Installa sul telefono',
    installSub: 'Schermata Home • Offline',
    addToHome: 'Installa',
    comingSoonStores: 'App Android e iOS in arrivo',
    essentialsTopics: 'Essenziali',
    activeCount: '{n} lingue',
    hearPhrase: 'Ascolta',
  },
  pt: {
    uiLanguageLabel: 'Idioma do app',
    uiLanguageHint: 'Só botões e ajuda. As cartas ficam à parte.',
    nativeLanguageHint: 'O significado da carta aparece neste idioma.',
    nextTopics: 'Seguinte (temas)',
    nextSetup: 'Seguinte (definições)',
    nextPlayers: 'Seguinte (jogadores)',
    stepOf: 'Passo {n} de {total}',
    stepLanguages: 'Idiomas e nível',
    stepTopics: 'Temas',
    stepSetup: 'Definições',
    stepPlayers: 'Nomes',
    tapMascot: 'Pronto para a festa!',
    onlineMultiplayer: 'Online (Discord / Meet)',
    installApp: 'Instalar no telemóvel',
    installSub: 'Ecrã inicial • Offline',
    addToHome: 'Instalar',
    comingSoonStores: 'Apps Android e iOS em breve',
    essentialsTopics: 'Essenciais',
    activeCount: '{n} idiomas',
    hearPhrase: 'Ouvir',
  },
  ar: {
    uiLanguageLabel: 'لغة التطبيق',
    uiLanguageHint: 'الأزرار والمساعدة فقط. لغات البطاقات منفصلة.',
    nativeLanguageHint: 'معنى البطاقة يظهر بهذه اللغة.',
    nextTopics: 'التالي (المواضيع)',
    nextSetup: 'التالي (الإعدادات)',
    nextPlayers: 'التالي (اللاعبون)',
    stepOf: 'الخطوة {n} من {total}',
    stepLanguages: 'اللغات والمستوى',
    stepTopics: 'المواضيع',
    stepSetup: 'إعدادات المباراة',
    stepPlayers: 'أسماء اللاعبين',
    tapMascot: 'جاهز للحفل! اضغطني',
    onlineMultiplayer: 'لعب عبر الإنترنت (ديسكورد / ميت)',
    installApp: 'تثبيت على الجوال',
    installSub: 'الشاشة الرئيسية • دون إنترنت',
    addToHome: 'تثبيت',
    comingSoonStores: 'تطبيقات أندرويد وiOS قريبًا',
    essentialsTopics: 'الأساسيات',
    activeCount: '{n} لغات',
    hearPhrase: 'استمع',
  },
  tr: {
    uiLanguageLabel: 'Uygulama dili',
    uiLanguageHint: 'Sadece düğmeler ve yardım. Kart dilleri ayrı.',
    nativeLanguageHint: 'Kart anlamı bu dilde görünür.',
    nextTopics: 'İleri (konular)',
    nextSetup: 'İleri (ayarlar)',
    nextPlayers: 'İleri (oyuncular)',
    stepOf: 'Adım {n} / {total}',
    stepLanguages: 'Diller ve seviye',
    stepTopics: 'Konular',
    stepSetup: 'Ayarlar',
    stepPlayers: 'Oyuncu adları',
    tapMascot: 'Partiye hazır! Dokun',
    onlineMultiplayer: 'Çevrimiçi (Discord / Meet)',
    installApp: 'Telefona yükle',
    installSub: 'Ana ekran • Çevrimdışı',
    addToHome: 'Yükle',
    comingSoonStores: 'Android ve iOS yakında',
    essentialsTopics: 'Temel konular',
    activeCount: '{n} dil',
    hearPhrase: 'Dinle',
  },
  pl: {
    uiLanguageLabel: 'Język aplikacji',
    uiLanguageHint: 'Tylko przyciski i pomoc. Karty osobno.',
    nativeLanguageHint: 'Znaczenie karty w tym języku.',
    nextTopics: 'Dalej (tematy)',
    nextSetup: 'Dalej (ustawienia)',
    nextPlayers: 'Dalej (gracze)',
    stepOf: 'Krok {n} z {total}',
    stepLanguages: 'Języki i poziom',
    stepTopics: 'Tematy',
    stepSetup: 'Ustawienia',
    stepPlayers: 'Imiona',
    tapMascot: 'Gotowi na imprezę!',
    onlineMultiplayer: 'Online (Discord / Meet)',
    installApp: 'Zainstaluj na telefonie',
    installSub: 'Ekran główny • Offline',
    addToHome: 'Zainstaluj',
    comingSoonStores: 'Aplikacje Android i iOS wkrótce',
    essentialsTopics: 'Najważniejsze',
    activeCount: '{n} języki',
    hearPhrase: 'Słuchaj',
  },
  uk: {
    uiLanguageLabel: 'Мова програми',
    uiLanguageHint: 'Лише кнопки та довідка. Картки окремо.',
    nativeLanguageHint: 'Значення картки цією мовою.',
    nextTopics: 'Далі (теми)',
    nextSetup: 'Далі (налаштування)',
    nextPlayers: 'Далі (гравці)',
    stepOf: 'Крок {n} з {total}',
    stepLanguages: 'Мови та рівень',
    stepTopics: 'Теми',
    stepSetup: 'Налаштування',
    stepPlayers: 'Імена',
    tapMascot: 'Готові до вечірки!',
    onlineMultiplayer: 'Онлайн (Discord / Meet)',
    installApp: 'Встановити на телефон',
    installSub: 'На головний екран • Офлайн',
    addToHome: 'Встановити',
    comingSoonStores: 'Додатки Android і iOS незабаром',
    essentialsTopics: 'Основне',
    activeCount: '{n} мови',
    hearPhrase: 'Слухати',
  },
  zh: {
    uiLanguageLabel: '应用语言',
    uiLanguageHint: '只改按钮和帮助，不影响卡片语言。',
    nativeLanguageHint: '卡片释义用这种语言显示。',
    nextTopics: '下一步（主题）',
    nextSetup: '下一步（设置）',
    nextPlayers: '下一步（玩家）',
    stepOf: '第 {n} / {total} 步',
    stepLanguages: '语言和级别',
    stepTopics: '主题',
    stepSetup: '比赛设置',
    stepPlayers: '玩家名字',
    tapMascot: '准备好派对！点我',
    onlineMultiplayer: '在线对战（Discord / Meet）',
    installApp: '安装到手机',
    installSub: '添加到主屏幕 • 可离线',
    addToHome: '安装',
    comingSoonStores: '安卓和 iOS 商店即将上线',
    essentialsTopics: '常用主题',
    activeCount: '{n} 种语言',
    hearPhrase: '听',
  },
  ja: {
    uiLanguageLabel: 'アプリの言語',
    uiLanguageHint: 'ボタンとヘルプだけ。カード言語は別です。',
    nativeLanguageHint: 'カードの意味はこの言語で出ます。',
    nextTopics: '次へ（トピック）',
    nextSetup: '次へ（設定）',
    nextPlayers: '次へ（プレイヤー）',
    stepOf: 'ステップ {n} / {total}',
    stepLanguages: '言語とレベル',
    stepTopics: 'トピック',
    stepSetup: '設定',
    stepPlayers: '名前',
    tapMascot: 'パーティー開始！タップして',
    onlineMultiplayer: 'オンライン（Discord / Meet）',
    installApp: 'スマホにインストール',
    installSub: 'ホーム画面に追加 • オフライン',
    addToHome: 'インストール',
    comingSoonStores: 'Android / iOS アプリ近日公開',
    essentialsTopics: 'よく使う話題',
    activeCount: '{n} 言語',
    hearPhrase: '聞く',
  },
  ko: {
    uiLanguageLabel: '앱 언어',
    uiLanguageHint: '버튼과 도움말만 바뀝니다. 카드 언어는 따로입니다.',
    nativeLanguageHint: '카드 뜻이 이 언어로 보여요.',
    nextTopics: '다음 (주제)',
    nextSetup: '다음 (설정)',
    nextPlayers: '다음 (플레이어)',
    stepOf: '{total} 중 {n}단계',
    stepLanguages: '언어와 레벨',
    stepTopics: '주제',
    stepSetup: '설정',
    stepPlayers: '이름',
    tapMascot: '파티 준비! 눌러보세요',
    onlineMultiplayer: '온라인 (Discord / Meet)',
    installApp: '휴대폰에 설치',
    installSub: '홈 화면 추가 • 오프라인',
    addToHome: '설치',
    comingSoonStores: '안드로이드·iOS 앱 곧 출시',
    essentialsTopics: '필수 주제',
    activeCount: '{n}개 언어',
    hearPhrase: '듣기',
  },
  hi: {
    uiLanguageLabel: 'ऐप की भाषा',
    uiLanguageHint: 'केवल बटन और मदद। कार्ड की भाषा अलग रहेगी।',
    nativeLanguageHint: 'कार्ड का अर्थ इस भाषा में दिखेगा।',
    nextTopics: 'आगे (विषय)',
    nextSetup: 'आगे (सेटिंग)',
    nextPlayers: 'आगे (खिलाड़ी)',
    stepOf: 'चरण {n} / {total}',
    stepLanguages: 'भाषा और स्तर',
    stepTopics: 'विषय',
    stepSetup: 'सेटिंग',
    stepPlayers: 'नाम',
    tapMascot: 'पार्टी के लिए तैयार! टैप करो',
    onlineMultiplayer: 'ऑनलाइन (Discord / Meet)',
    installApp: 'फ़ोन पर इंस्टॉल',
    installSub: 'होम स्क्रीन • ऑफ़लाइन',
    addToHome: 'इंस्टॉल',
    comingSoonStores: 'Android और iOS ऐप जल्द',
    essentialsTopics: 'ज़रूरी विषय',
    activeCount: '{n} भाषाएँ',
    hearPhrase: 'सुनो',
  },
};

export function tUI(lang: Language): any {
  const code = resolveUiLang(lang);
  const base = TRANSLATIONS[code] || TRANSLATIONS.en || {};
  const extra = UI_STRINGS[code] || UI_STRINGS.en;
  return { ...base, ...extra };
}

export function tf(lang: Language, key: string, vars?: Record<string, string | number>): string {
  const pack = tUI(lang);
  let s = (pack[key] as string) || UI_STRINGS.en[key] || key;
  if (vars) {
    s = s.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));
  }
  return s;
}
