import { Language } from './types';
import { TRANSLATIONS } from './translations';

export function resolveUiLang(lang: Language | string): Language {
  if (lang === 'en-US') return 'en' as Language;
  return (lang as Language) || 'en';
}

export function isRtlLang(lang: Language | string): boolean {
  return lang === 'fa' || lang === 'ar' || lang === 'ur' || lang === 'he' || lang === 'ku';
}

export const UI_STRINGS: Record<string, Record<string, string>> = {
  fa: {
    players: 'بازیکن',
    uiLanguageLabel: 'زبان برنامه',
    uiLanguageHint: 'فقط دکمه‌ها و متن راهنما. روی کارت‌ها اثر ندارد.',
    nativeLanguageHint: 'معنی کارت به این زبان دیده می‌شود.',
    nextTopics: 'مرحله بعد (موضوعات)',
    nextSetup: 'مرحله بعد (تنظیمات)',
    nextPlayers: 'مرحله بعد (بازیکنان)',
    stepOf: 'مرحله {n} از {total}',
    stepLanguages: 'زبان‌ها و سطح',
    stepTopics: 'موضوعات',
    stepSetup: 'تنظیمات مسابقه',
    stepPlayers: 'نام بازیکنان',
    tapMascot: 'بزن رو من شاد شی!',
    onlineMultiplayer: 'بازی آنلاین (دیسکورد / میت)',
    installApp: 'نصب روی گوشی (PWA)',
    installSub: 'افزودن به صفحه اصلی • آفلاین',
    addToHome: 'نصب / افزودن',
    comingSoonStores: 'نسخه اندروید و iOS به‌زودی در استورها',
    essentialsTopics: 'موضوعات ضروری',
    activeCount: '{n} زبان',
    hearPhrase: 'بشنو',
    singlePlayer: 'تمرین تک‌نفره',
    singlePlayerSub: 'فلش‌کارت و گفتار هوشمند با تصحیح آنی',
    flashcards: 'فلش‌کارت‌ها',
    audioOnlyMode: 'فقط صدا (شنیداری)',
    textAndAudioMode: 'متن + صدا',
    speakOrType: 'با میکروفون صحبت کنید یا بنویسید',
    listening: 'در حال گوش دادن...',
    tapToSpeak: 'لمس میکروفون برای صحبت',
    stopListening: 'توقف گوش دادن',
    checkAnswer: 'بررسی پاسخ',
    tryAgain: 'تصحیح جواب',
    nextCard: 'کارت بعدی',
    showAnswer: 'نمایش پاسخ کامل',
    revealHint: 'نمایش متن / راهنما',
    leaderboard: 'لیدربرد و رکوردها',
    reportCard: 'کارنامه آموزشی',
    weakCards: 'کارت‌های نیازمند تمرین مجدد',
    practiceWeakCards: 'تمرین کارت‌های مشکل‌دار',
    cardOf: 'کارت {n} از {total}',
    accuracy: 'دقت پاسخ‌گویی',
    score: 'امتیاز',
    streak: 'زنجیره درست',
    enterAnswerPlaceholder: 'جمله را اینجا تایپ کنید یا بگویید...',
    micNotSupported: 'مرورگر شما از تشخیص گفتار پشتیبانی نمی‌کند، لطفاً تایپ کنید.',
    answerFeedbackCorrect: 'آفرین! کاملاً درست است.',
    answerFeedbackCorrected: 'عالی! جواب را با موفقیت تصحیح کردی.',
    tableSeatingTitle: 'چیدمان دور میز',
    tableSeatingTip: 'هم‌تیمی‌ها دقیقاً روبروی هم می‌نشینند! چرخش نوبت ساعت‌گرد است.',
    tagline: 'گوشی رو دست‌به‌دست کن. زمان رو شکست بده. صحبت کن.',
    startNewGame: 'شروع بازی جدید',
    singlePlayerBtn: 'تک‌نفره',
    onlineRoom: 'اتاق آنلاین',
    gameHistory: 'تاریخچه بازی‌ها',
    gameRules: 'راهنمای بازی و قوانین',
    profileLeaderboard: 'پروفایل و لیدربرد',
    changeLanguage: 'تغییر زبان برنامه',
    vocabParty: 'مسابقه واژگان و مکالمه تیمی',
    multiLingual: 'چندزبانه',
    matchSettingsSubtitle: 'تنظیمات زبان، موضوعات و قوانین مسابقه',
    playersAndRounds: 'بازیکنان و دورهای مسابقه',
    totalPlayersLabel: 'تعداد کل بازیکنان (۲ بازیکن در هر تیم):',
    teams: 'تیم',
    team: 'تیم',
    playerNamesAndTeams: 'اسامی بازیکنان و تیم‌ها:',
    randomize: 'اسامی تصادفی 🎲',
    targetLanguages: 'زبان‌های هدف مسابقه (در حال یادگیری)',
    targetLanguagesSub: 'کلمات کارت‌ها به این زبان‌ها نمایش داده می‌شوند',
    searchLanguagePlaceholder: 'جستجوی زبان جدید برای تگ شدن...',
    all38Languages: '۳۸ زبان ▾',
    removeLanguage: 'حذف این زبان',
    added: 'تگ شده ✓',
    add: '+ افزودن',
    cefrLevel: 'سطح دشواری و تسلط (CEFR)',
    nativeLanguage: 'زبان مادری و راهنمای کارت‌ها',
    changeNative: 'تغییر مادری ▾',
    appUiLanguage: 'زبان رابط برنامه',
    changeUi: 'تغییر رابط ▾',
    seatedStart: 'نشستیم! شروع دور ۱',
    describeFor: 'این کلمه را برای {player} توصیف کنید:',
    activeTurn: 'نوبت توضیح و حدس:',
    guessedCorrectly: 'درست حدس زد! (+امتیاز)',
    passWrong: 'پاس / خطا',
    audioPronunciation: 'پخش تلفظ صوتی',
    timeAdded: '⏱️ ۱۰+ ثانیه زمان اضافه شد!',
    hintActivated: '💡 راهنما فعال شد!',
    almostCorrect: 'تقریباً درست (رأی جمعی)',
    listeningTeammates: '🎙️ در حال گوش دادن به هم‌تیمی‌ها...',
    yourTurnToGuess: '🙈 نوبت حدس زدن شماست!',
    cardHiddenGuesser: 'کارت از روی صفحه شما مخفی است تا بازی لو نرود. به صدای هم‌تیمی‌هایتان در تماس صوتی گوش دهید و کلمه هدف را حدس بزنید!',
    championTeam: 'تیم قهرمان:',
    matchComplete: 'پایان مسابقه! 🏆',
    shareScorecard: 'اشتراک‌گذاری کارنامه مسابقه 📤',
    exitToMenu: 'خروج به صفحه اصلی',
    react: 'واکنش:',
    roomCode: 'کد اتاق:',
    freeVoice: 'تلفن رایگان',
    joinCall: 'ورود به تماس',
    waitingHost: 'منتظر میزبان برای زدن دکمه شروع بازی...',
    copied: 'کپی شد',
    copy: 'کپی کد',
    directLink: 'لینک مستقیم',
    connectedPlayersCount: 'بازیکنان متصل ({n} نفر):',
    clickToSwitchTeam: 'روی نام تیم برای جابجایی کلیک کنید',
    noPlayers: 'بدون بازیکن',
    youBadge: 'من',
    joinTeam: 'عضویت',
    roundDurationLabel: 'مدت هر راند:',
    secondsUnit: 'ثانیه',
    enterRoomCode: 'کد ۵ حرفی اتاق را وارد کنید:',
    joinGameBtn: 'ورود به اتاق',
    createRoomBtn: 'ایجاد اتاق آنلاین جدید',
    close: 'بستن',
    refresh: 'تازه‌سازی',
    fastOffline: 'اجرای سریع، تمام‌صفحه و آفلاین',
    installDirect: 'نصب مستقیم با یک کلیک',
    worksOffline: 'آفلاین و بدون مصرف نت',
    toggleTableSeating: 'نمایش / مخفی‌سازی چیدمان دور میز',
    gameSettings: 'تنظیمات بازی',
    searchLanguages: 'جستجوی زبان... (مثلاً فارسی، English، de)',
    myNativeLanguage: 'زبان من:',
    languagesIWantToLearn: 'زبان‌هایی که می‌خوام یاد بگیرم:',
    activeTargetsCount: '{n} زبان فعال',
    noLanguagesFound: 'زبانی یافت نشد',
    atLeastOneLanguage: 'حداقل یک زبان برای یادگیری باید انتخاب شود. راه‌حل: روی یکی از زبان‌های دیگر کلیک کنید تا فعال شود.',
    howManyPlayers: 'چند نفره؟',
    playersCount: '{n} نفر',
    roundsCountLabel: 'تعداد راند',
    turnTimeLabel: 'زمان هر دور',
    autoPronounce: 'تلفظ خودکار',
    autoPronounceDesc: 'کارت که اومد، کلمه خوانده می‌شه',
    hotSeat: 'صندلی داغ',
    hotSeatDesc: 'گوشی سریع دست‌به‌دست می‌شه',
    cardDirection: 'جهت ترجمه کارت‌ها',
    dirNativeToTarget: 'فارسی به انگلیسی',
    dirTargetToNative: 'انگلیسی به فارسی',
    dirBoth: 'هر دو',
    nextStartGame: 'مرحله بعد: شروع بازی',
    guideTitle: 'راهنما',
    guideText1: 'زبان مبدأ و زبان‌هایی که می‌خوای یاد بگیری رو انتخاب کن؛ می‌تونی چند زبان با هم بزنی.',
    guideText2: 'راند و زمان دور رو مثل قفل چمدون بالا و پایین کن یا با دکمه‌های کم و زیاد تنظیم کن.',
    gotIt: 'فهمیدم',
    soundActive: 'صدای بازی فعال',
    soundMuted: 'صدای بازی غیرفعال'
  },

  en: {
    uiLanguageLabel: 'App language',
    uiLanguageHint: 'Buttons and help only. Card languages stay separate.',
    nativeLanguageHint: 'Card meanings appear in this language.',
    nextTopics: 'Next (topics)',
    nextSetup: 'Next (setup)',
    nextPlayers: 'Next (players)',
    stepOf: 'Step {n} of {total}',
    stepLanguages: 'Languages & level',
    stepTopics: 'Topics',
    stepSetup: 'Match settings',
    stepPlayers: 'Player names',
    tapMascot: 'Ready to Party! Tap Me!',
    onlineMultiplayer: 'Online multiplayer (Discord / Meet)',
    installApp: 'Install on phone',
    installSub: 'Add to Home Screen • Works offline',
    addToHome: 'Install / Add',
    comingSoonStores: 'Android & iOS store apps coming soon',
    essentialsTopics: 'Essentials',
    activeCount: '{n} languages',
    hearPhrase: 'Listen',
    singlePlayer: 'Single-Player',
    singlePlayerSub: 'Smart flashcards & voice practice',
    flashcards: 'Flashcards',
    audioOnlyMode: 'Audio Only (Listening Challenge)',
    textAndAudioMode: 'Text + Audio',
    speakOrType: 'Speak with mic or type the answer',
    listening: 'Listening...',
    tapToSpeak: 'Tap Mic to Speak',
    stopListening: 'Stop Listening',
    checkAnswer: 'Check Answer',
    tryAgain: 'Try Again / Correct',
    nextCard: 'Next Card',
    showAnswer: 'Show Answer',
    revealHint: 'Reveal Text / Hint',
    leaderboard: 'Leaderboard',
    reportCard: 'Learning Report Card',
    weakCards: 'Cards to Review',
    practiceWeakCards: 'Practice Weak Cards Now',
    cardOf: 'Card {n} of {total}',
    accuracy: 'Accuracy',
    score: 'Score',
    streak: 'Streak',
    enterAnswerPlaceholder: 'Type or speak the sentence here...',
    micNotSupported: 'Speech recognition not supported in this browser, please type.',
    answerFeedbackCorrect: 'Awesome! Completely correct.',
    answerFeedbackCorrected: 'Great job correcting your answer!',
    tableSeatingTitle: 'Table Seating Guide',
    tableSeatingTip: 'Teammates sit directly opposite each other! Clockwise turns.',
    tagline: 'Pass one phone. Beat the clock. Speak.',
    startNewGame: 'Start New Game',
    singlePlayerBtn: 'Single Player',
    onlineRoom: 'Online Room',
    gameHistory: 'Game History',
    gameRules: 'Game Rules & Guide',
    profileLeaderboard: 'Profile & Leaderboard',
    changeLanguage: 'Change app language',
    vocabParty: 'VOCAB & CONVERSATION PARTY',
    multiLingual: 'Multi-Lingual',
    matchSettingsSubtitle: 'Match settings, languages & rules',
    playersAndRounds: 'Players & Match Rounds',
    totalPlayersLabel: 'Total Players (2 per team):',
    teams: 'Teams',
    team: 'Team',
    playerNamesAndTeams: 'Player Names & Teams:',
    randomize: 'Randomize 🎲',
    targetLanguages: 'Target Languages (Learning)',
    targetLanguagesSub: 'Cards will test words in these languages',
    searchLanguagePlaceholder: 'Search language to tag...',
    all38Languages: 'All 38 ▾',
    removeLanguage: 'Remove language',
    added: 'Added ✓',
    add: '+ Add',
    cefrLevel: 'Proficiency Level (CEFR)',
    nativeLanguage: 'Native / Support Language',
    changeNative: 'Change ▾',
    appUiLanguage: 'App UI Language',
    changeUi: 'Change UI ▾',
    seatedStart: "We're Seated! Start Round 1",
    describeFor: 'Describe this word for {player}:',
    activeTurn: 'Active Guesser / Turn:',
    guessedCorrectly: 'Guessed Correctly! (+pts)',
    passWrong: 'Pass / Wrong',
    audioPronunciation: 'Audio Pronunciation',
    timeAdded: '⏱️ +10s Time Added!',
    hintActivated: '💡 Hint Activated!',
    almostCorrect: 'Almost Correct (Vote)',
    listeningTeammates: '🎙️ Listening to teammates...',
    yourTurnToGuess: "🙈 It's your turn to guess!",
    cardHiddenGuesser: 'The card is hidden on your screen to avoid spoilers. Listen to your teammates on the voice call and guess the target word!',
    championTeam: 'Champion Team:',
    matchComplete: 'Match Complete! 🏆',
    shareScorecard: 'Share Match Scorecard 📤',
    exitToMenu: 'Exit to Main Menu',
    react: 'React:',
    roomCode: 'Room Code:',
    freeVoice: 'Free Voice',
    joinCall: 'Join Call',
    waitingHost: 'Waiting for host to start the game...',
    copied: 'Copied',
    copy: 'Copy',
    directLink: 'Link',
    connectedPlayersCount: 'Connected Players ({n}):',
    clickToSwitchTeam: 'Click team to switch',
    noPlayers: 'No players',
    youBadge: 'You',
    joinTeam: 'Join',
    roundDurationLabel: 'Round Duration:',
    secondsUnit: 'seconds',
    enterRoomCode: 'Enter 5-character Room Code:',
    joinGameBtn: 'Join Room',
    createRoomBtn: 'Create New Online Room',
    close: 'Close',
    refresh: 'Refresh',
    fastOffline: 'Fast, Fullscreen & Offline',
    installDirect: 'Instant 1-Click Install',
    worksOffline: 'Works 100% Offline',
    toggleTableSeating: 'Toggle Table Seating',
    gameSettings: 'Game Settings',
    searchLanguages: 'Search languages... (e.g. English, Dutch, de)',
    myNativeLanguage: 'My Native Language:',
    languagesIWantToLearn: 'Languages I Want to Learn:',
    activeTargetsCount: '{n} active',
    noLanguagesFound: 'No languages found',
    atLeastOneLanguage: 'At least one learning language must be selected. Fix: Tap another language chip to select it.',
    howManyPlayers: 'How many players?',
    playersCount: '{n} players',
    roundsCountLabel: 'Number of Rounds',
    turnTimeLabel: 'Turn Duration',
    autoPronounce: 'Auto Pronunciation',
    autoPronounceDesc: 'When card appears, the word is spoken',
    hotSeat: 'Hot Seat',
    hotSeatDesc: 'Fast phone handoff between players',
    cardDirection: 'Card Translation Direction',
    dirNativeToTarget: 'Native → Target',
    dirTargetToNative: 'Target → Native',
    dirBoth: 'Both',
    nextStartGame: 'Next: Start Game',
    guideTitle: 'Guide',
    guideText1: 'Select your native language and the languages you want to learn. You can pick multiple target languages at once.',
    guideText2: 'Scroll the luggage lock wheels up and down to adjust rounds and turn duration.',
    gotIt: 'Got it',
    soundActive: 'Sound Active',
    soundMuted: 'Sound Muted'
  },

  de: {
    uiLanguageLabel: 'App-Sprache',
    uiLanguageHint: 'Nur Tasten und Hilfe. Karten bleiben getrennt.',
    nativeLanguageHint: 'Kartenbedeutung in dieser Sprache.',
    nextTopics: 'Weiter (Themen)',
    nextSetup: 'Weiter (Einstellungen)',
    nextPlayers: 'Weiter (Spieler)',
    stepOf: 'Schritt {n} von {total}',
    stepLanguages: 'Sprachen & Niveau',
    stepTopics: 'Themen',
    stepSetup: 'Spieleinstellungen',
    stepPlayers: 'Spielernamen',
    tapMascot: 'Party ready! Tippe mich!',
    onlineMultiplayer: 'Online (Discord / Meet)',
    installApp: 'Aufs Handy installieren',
    installSub: 'Zum Startbildschirm • Offline',
    addToHome: 'Installieren',
    comingSoonStores: 'Android- und iOS-Apps folgen',
    essentialsTopics: 'Wichtigste',
    activeCount: '{n} Sprachen',
    hearPhrase: 'Hören',
    tagline: 'Gib das Handy weiter. Schlage die Uhr. Sprich.',
    startNewGame: 'Neues Spiel',
    singlePlayerBtn: 'Einzelspieler',
    onlineRoom: 'Online-Raum',
    gameHistory: 'Spielverlauf',
    gameRules: 'Spielregeln & Anleitung',
    profileLeaderboard: 'Profil & Bestenliste',
    changeLanguage: 'App-Sprache ändern',
    vocabParty: 'WORTSCHATZ & PARTY-SPIEL',
    multiLingual: 'Mehrsprachig',
    matchSettingsSubtitle: 'Spieleinstellungen, Sprachen & Regeln',
    playersAndRounds: 'Spieler & Runden',
    totalPlayersLabel: 'Gesamtspieler (2 pro Team):',
    teams: 'Teams',
    team: 'Team',
    playerNamesAndTeams: 'Spielernamen & Teams:',
    randomize: 'Zufällig 🎲',
    targetLanguages: 'Zielsprachen (Lernen)',
    targetLanguagesSub: 'Karten testen Wörter in diesen Sprachen',
    searchLanguagePlaceholder: 'Sprache suchen...',
    all38Languages: 'Alle 38 ▾',
    removeLanguage: 'Sprache entfernen',
    added: 'Hinzugefügt ✓',
    add: '+ Hinzufügen',
    cefrLevel: 'Schwierigkeit & Niveau (CEFR)',
    nativeLanguage: 'Muttersprache / Hilfssprache',
    changeNative: 'Ändern ▾',
    appUiLanguage: 'App-Benutzeroberfläche',
    changeUi: 'Sprache ▾',
    tableSeatingTitle: 'Sitzordnung am Tisch',
    tableSeatingTip: 'Teamkollegen sitzen sich direkt gegenüber! Reihum im Uhrzeigersinn.',
    seatedStart: 'Wir sitzen! Runde 1 starten',
    describeFor: 'Beschreibe dieses Wort für {player}:',
    activeTurn: 'Am Zug / Rater:',
    guessedCorrectly: 'Richtig erraten! (+Pkt)',
    passWrong: 'Passen / Falsch',
    audioPronunciation: 'Aussprache anhören',
    timeAdded: '⏱️ +10s Zeit hinzugefügt!',
    hintActivated: '💡 Hinweis aktiviert!',
    almostCorrect: 'Fast richtig (Abstimmung)',
    listeningTeammates: '🎙️ Höre den Teamkollegen zu...',
    yourTurnToGuess: '🙈 Du bist dran mit Raten!',
    cardHiddenGuesser: 'Die Karte ist auf deinem Bildschirm verdeckt. Höre deinen Teamkollegen im Audio-Chat zu und rate das Zielwort!',
    championTeam: 'Sieger-Team:',
    matchComplete: 'Match beendet! 🏆',
    shareScorecard: 'Ergebniskarte teilen 📤',
    exitToMenu: 'Zurück zum Hauptmenü',
    react: 'Reagiere:',
    roomCode: 'Raum-Code:',
    freeVoice: 'Kostenloses Audio',
    joinCall: 'Anruf beitreten',
    waitingHost: 'Warte auf Spielleiter zum Starten...',
    copied: 'Kopiert',
    copy: 'Kopieren',
    directLink: 'Link',
    connectedPlayersCount: 'Verbundene Spieler ({n}):',
    clickToSwitchTeam: 'Klicke auf ein Team zum Wechseln',
    noPlayers: 'Keine Spieler',
    youBadge: 'Du',
    joinTeam: 'Beitreten',
    roundDurationLabel: 'Rundendauer:',
    secondsUnit: 'Sekunden',
    enterRoomCode: '5-stelligen Raumcode eingeben:',
    joinGameBtn: 'Raum beitreten',
    createRoomBtn: 'Neuen Online-Raum erstellen',
    close: 'Schließen',
    refresh: 'Aktualisieren',
    fastOffline: 'Schnell, Vollbild & Offline',
    installDirect: '1-Klick-Installation',
    worksOffline: '100% Offline nutzbar',
    toggleTableSeating: 'Sitzordnung umschalten'
  },

  fr: {
    uiLanguageLabel: 'Langue de l’app',
    uiLanguageHint: 'Boutons et aide seulement. Les cartes restent séparées.',
    nativeLanguageHint: 'Le sens des cartes s’affiche dans cette langue.',
    nextTopics: 'Suivant (thèmes)',
    nextSetup: 'Suivant (réglages)',
    nextPlayers: 'Suivant (joueurs)',
    stepOf: 'Étape {n} sur {total}',
    stepLanguages: 'Langues et niveau',
    stepTopics: 'Thèmes',
    stepSetup: 'Réglages',
    stepPlayers: 'Noms des joueurs',
    tapMascot: 'Prêt à faire la fête !',
    onlineMultiplayer: 'En ligne (Discord / Meet)',
    installApp: 'Installer sur le téléphone',
    installSub: 'Écran d’accueil • Hors ligne',
    addToHome: 'Installer',
    comingSoonStores: 'Apps Android et iOS bientôt',
    essentialsTopics: 'Essentiels',
    activeCount: '{n} langues',
    hearPhrase: 'Écouter',
    tagline: 'Passe le téléphone. Bats le chrono. Parle.',
    startNewGame: 'Nouvelle partie',
    singlePlayerBtn: 'Solo',
    onlineRoom: 'Salon en ligne',
    gameHistory: 'Historique des parties',
    gameRules: 'Règles et guide du jeu',
    profileLeaderboard: 'Profil et classement',
    changeLanguage: 'Changer la langue de l’app',
    vocabParty: 'JEU DE VOCABULAIRE ET SOIRÉE',
    multiLingual: 'Multilingue',
    matchSettingsSubtitle: 'Réglages, langues et règles',
    playersAndRounds: 'Joueurs et manches',
    totalPlayersLabel: 'Total des joueurs (2 par équipe) :',
    teams: 'Équipes',
    team: 'Équipe',
    playerNamesAndTeams: 'Noms des joueurs et équipes :',
    randomize: 'Aléatoire 🎲',
    targetLanguages: 'Langues cibles (Apprentissage)',
    targetLanguagesSub: 'Les cartes testeront ces langues',
    searchLanguagePlaceholder: 'Rechercher une langue...',
    all38Languages: 'Les 38 ▾',
    removeLanguage: 'Supprimer la langue',
    added: 'Ajouté ✓',
    add: '+ Ajouter',
    cefrLevel: 'Niveau de maîtrise (CEFR)',
    nativeLanguage: 'Langue maternelle / support',
    changeNative: 'Modifier ▾',
    appUiLanguage: 'Langue de l’interface',
    changeUi: 'Changer ▾',
    tableSeatingTitle: 'Plan de table',
    tableSeatingTip: 'Les coéquipiers s’assoient face à face ! Tourne dans le sens horaire.',
    seatedStart: 'On est installés ! Lancer la manche 1',
    describeFor: 'Décris ce mot pour {player} :',
    activeTurn: 'Au tour de deviner :',
    guessedCorrectly: 'Bien deviné ! (+pts)',
    passWrong: 'Passer / Faux',
    audioPronunciation: 'Écouter la prononciation',
    timeAdded: '⏱️ +10s de temps ajouté !',
    hintActivated: '💡 Indice activé !',
    almostCorrect: 'Presque correct (Vote)',
    listeningTeammates: '🎙️ À l’écoute de l’équipe...',
    yourTurnToGuess: '🙈 C’est à toi de deviner !',
    cardHiddenGuesser: 'La carte est masquée sur votre écran. Écoutez vos coéquipiers dans l’appel vocal et devinez le mot !',
    championTeam: 'Équipe championne :',
    matchComplete: 'Partie terminée ! 🏆',
    shareScorecard: 'Partager le bilan 📤',
    exitToMenu: 'Retour au menu principal',
    react: 'Réagir :',
    roomCode: 'Code salon :',
    freeVoice: 'Voix gratuite',
    joinCall: 'Rejoindre l’appel',
    waitingHost: 'En attente de l’hôte pour démarrer...',
    copied: 'Copié',
    copy: 'Copier',
    directLink: 'Lien',
    connectedPlayersCount: 'Joueurs connectés ({n}) :',
    clickToSwitchTeam: 'Cliquez sur une équipe pour changer',
    noPlayers: 'Aucun joueur',
    youBadge: 'Moi',
    joinTeam: 'Rejoindre',
    roundDurationLabel: 'Durée de la manche :',
    secondsUnit: 'secondes',
    enterRoomCode: 'Entrez le code salon à 5 lettres :',
    joinGameBtn: 'Rejoindre le salon',
    createRoomBtn: 'Créer un nouveau salon',
    close: 'Fermer',
    refresh: 'Actualiser',
    fastOffline: 'Rapide, plein écran & hors-ligne',
    installDirect: 'Installation directe en 1 clic',
    worksOffline: 'Fonctionne 100% hors ligne',
    toggleTableSeating: 'Afficher / masquer la disposition'
  },

  es: {
    uiLanguageLabel: 'Idioma de la app',
    uiLanguageHint: 'Solo botones y ayuda. Las cartas van aparte.',
    nativeLanguageHint: 'El significado de la carta sale en este idioma.',
    nextTopics: 'Siguiente (temas)',
    nextSetup: 'Siguiente (ajustes)',
    nextPlayers: 'Siguiente (jugadores)',
    stepOf: 'Paso {n} de {total}',
    stepLanguages: 'Idiomas y nivel',
    stepTopics: 'Temas',
    stepSetup: 'Ajustes',
    stepPlayers: 'Nombres',
    tapMascot: '¡A la fiesta! Tócame',
    onlineMultiplayer: 'En línea (Discord / Meet)',
    installApp: 'Instalar en el móvil',
    installSub: 'Pantalla de inicio • Sin red',
    addToHome: 'Instalar',
    comingSoonStores: 'Apps de Android e iOS pronto',
    essentialsTopics: 'Esenciales',
    activeCount: '{n} idiomas',
    hearPhrase: 'Escuchar',
    tagline: 'Pasa el teléfono. Vence al reloj. Habla.',
    startNewGame: 'Nueva partida',
    singlePlayerBtn: 'Un jugador',
    onlineRoom: 'Sala online',
    gameHistory: 'Historial de partidas',
    gameRules: 'Reglas y guía del juego',
    profileLeaderboard: 'Perfil y clasificación',
    changeLanguage: 'Cambiar idioma de la app',
    vocabParty: 'FIESTA DE VOCABULARIO Y CONVERSACIÓN',
    multiLingual: 'Multilingüe',
    matchSettingsSubtitle: 'Ajustes, idiomas y reglas',
    playersAndRounds: 'Jugadores y rondas',
    totalPlayersLabel: 'Total de jugadores (2 por equipo):',
    teams: 'Equipos',
    team: 'Equipo',
    playerNamesAndTeams: 'Nombres de jugadores y equipos:',
    randomize: 'Aleatorio 🎲',
    targetLanguages: 'Idiomas meta (Aprendiendo)',
    targetLanguagesSub: 'Las cartas mostrarán estas lenguas',
    searchLanguagePlaceholder: 'Buscar idioma...',
    all38Languages: 'Los 38 ▾',
    removeLanguage: 'Eliminar idioma',
    added: 'Añadido ✓',
    add: '+ Añadir',
    cefrLevel: 'Nivel de dificultad (CEFR)',
    nativeLanguage: 'Idioma materno / apoyo',
    changeNative: 'Cambiar ▾',
    appUiLanguage: 'Idioma de la interfaz',
    changeUi: 'Cambiar ▾',
    tableSeatingTitle: 'Disposición en la mesa',
    tableSeatingTip: '¡Los compañeros se sientan frente a frente! Sentido horario.',
    seatedStart: '¡Listos! Empezar ronda 1',
    describeFor: 'Describe esta palabra para {player}:',
    activeTurn: 'Turno de adivinar:',
    guessedCorrectly: '¡Correcto! (+pts)',
    passWrong: 'Pasar / Error',
    audioPronunciation: 'Escuchar pronunciación',
    timeAdded: '⏱️ ¡+10s añadidos!',
    hintActivated: '💡 ¡Pista activada!',
    almostCorrect: 'Casi correcto (Voto)',
    listeningTeammates: '🎙️ Escuchando a los compañeros...',
    yourTurnToGuess: '🙈 ¡Es tu turno de adivinar!',
    cardHiddenGuesser: 'La carta está oculta en tu pantalla para no revelar nada. ¡Escucha a tus compañeros en la llamada y adivina la palabra!',
    championTeam: 'Equipo campeón:',
    matchComplete: '¡Partida completada! 🏆',
    shareScorecard: 'Compartir resultado 📤',
    exitToMenu: 'Volver al menú principal',
    react: 'Reaccionar:',
    roomCode: 'Código de sala:',
    freeVoice: 'Voz gratis',
    joinCall: 'Unirse a la llamada',
    waitingHost: 'Esperando a que el anfitrión empiece...',
    copied: 'Copiado',
    copy: 'Copiar',
    directLink: 'Enlace',
    connectedPlayersCount: 'Jugadores conectados ({n}):',
    clickToSwitchTeam: 'Toca un equipo para cambiar',
    noPlayers: 'Sin jugadores',
    youBadge: 'Yo',
    joinTeam: 'Unirme',
    roundDurationLabel: 'Duración de ronda:',
    secondsUnit: 'segundos',
    enterRoomCode: 'Introduce el código de 5 letras:',
    joinGameBtn: 'Entrar a la sala',
    createRoomBtn: 'Crear nueva sala online',
    close: 'Cerrar',
    refresh: 'Actualizar',
    fastOffline: 'Rápido, pantalla completa y sin red',
    installDirect: 'Instalación en 1 clic',
    worksOffline: 'Funciona 100% sin conexión',
    toggleTableSeating: 'Mostrar / ocultar mesa'
  },

  it: {
    uiLanguageLabel: 'Lingua dell’app',
    uiLanguageHint: 'Solo pulsanti e guida. Le carte restano separate.',
    nativeLanguageHint: 'Il significato della carta è in questa lingua.',
    nextTopics: 'Avanti (argomenti)',
    nextSetup: 'Avanti (impostazioni)',
    nextPlayers: 'Avanti (giocatori)',
    stepOf: 'Passo {n} di {total}',
    stepLanguages: 'Lingue e livello',
    stepTopics: 'Argomenti',
    stepSetup: 'Impostazioni',
    stepPlayers: 'Nomi',
    tapMascot: 'Pronto per la festa!',
    onlineMultiplayer: 'Online (Discord / Meet)',
    installApp: 'Installa sul telefono',
    installSub: 'Schermata Home • Offline',
    addToHome: 'Installa',
    comingSoonStores: 'App Android e iOS in arrivo',
    essentialsTopics: 'Essenziali',
    activeCount: '{n} lingue',
    hearPhrase: 'Ascolta',
    tagline: 'Passa il telefono. Batti il tempo. Parla.',
    startNewGame: 'Nuova partita',
    singlePlayerBtn: 'Giocatore singolo',
    onlineRoom: 'Stanza online',
    gameHistory: 'Cronologia partite',
    gameRules: 'Regole e guida del gioco',
    profileLeaderboard: 'Profilo e classifica',
    changeLanguage: 'Cambia lingua dell’app',
    vocabParty: 'PARTY GAME DI VOCABOLARIO E PARLATO',
    multiLingual: 'Multilingue',
    matchSettingsSubtitle: 'Impostazioni, lingue e regole',
    playersAndRounds: 'Giocatori e round',
    totalPlayersLabel: 'Totale giocatori (2 per squadra):',
    teams: 'Squadre',
    team: 'Squadra',
    playerNamesAndTeams: 'Nomi dei giocatori e squadre:',
    randomize: 'Casuale 🎲',
    targetLanguages: 'Lingue di arrivo (Studio)',
    targetLanguagesSub: 'Le carte testeranno queste lingue',
    searchLanguagePlaceholder: 'Cerca lingua...',
    all38Languages: 'Tutte le 38 ▾',
    removeLanguage: 'Rimuovi lingua',
    added: 'Aggiunto ✓',
    add: '+ Aggiungi',
    cefrLevel: 'Livello di competenza (CEFR)',
    nativeLanguage: 'Lingua madre / supporto',
    changeNative: 'Modifica ▾',
    appUiLanguage: 'Lingua dell’interfaccia',
    changeUi: 'Cambia ▾',
    tableSeatingTitle: 'Disposizione al tavolo',
    tableSeatingTip: 'I compagni di squadra siedono uno di fronte all’altro! Senso orario.',
    seatedStart: 'Siamo seduti! Inizia round 1',
    describeFor: 'Descrivi questa parola per {player}:',
    activeTurn: 'Turno di indovinare:',
    guessedCorrectly: 'Indovinato! (+pt)',
    passWrong: 'Passo / Errore',
    audioPronunciation: 'Ascolta pronuncia',
    timeAdded: '⏱️ +10s di tempo aggiunto!',
    hintActivated: '💡 Suggerimento attivo!',
    almostCorrect: 'Quasi corretto (Voto)',
    listeningTeammates: '🎙️ Ascoltando i compagni...',
    yourTurnToGuess: '🙈 È il tuo turno di indovinare!',
    cardHiddenGuesser: 'La carta è nascosta sul tuo schermo per non svelare nulla. Ascolta i compagni nella chiamata vocale e indovina la parola!',
    championTeam: 'Squadra campione:',
    matchComplete: 'Partita completata! 🏆',
    shareScorecard: 'Condividi pagella 📤',
    exitToMenu: 'Torna al menu principale',
    react: 'Reagisci:',
    roomCode: 'Codice stanza:',
    freeVoice: 'Voce gratuita',
    joinCall: 'Entra nella chiamata',
    waitingHost: 'In attesa che l’host avvii la partita...',
    copied: 'Copiato',
    copy: 'Copia',
    directLink: 'Link',
    connectedPlayersCount: 'Giocatori connessi ({n}):',
    clickToSwitchTeam: 'Clicca su una squadra per cambiare',
    noPlayers: 'Nessun giocatore',
    youBadge: 'Tu',
    joinTeam: 'Entra',
    roundDurationLabel: 'Durata round:',
    secondsUnit: 'secondi',
    enterRoomCode: 'Inserisci il codice stanza:',
    joinGameBtn: 'Entra nella stanza',
    createRoomBtn: 'Crea nuova stanza',
    close: 'Chiudi',
    refresh: 'Aggiorna',
    fastOffline: 'Veloce, a schermo intero e offline',
    installDirect: 'Installazione in 1 clic',
    worksOffline: 'Funziona 100% offline',
    toggleTableSeating: 'Mostra / nascondi tavolo'
  },

  nl: {
    uiLanguageLabel: 'App-taal',
    uiLanguageHint: 'Alleen knoppen en hulp. Kaarttalen blijven apart.',
    nativeLanguageHint: 'Betekenis van kaarten in deze taal.',
    nextTopics: 'Volgende (onderwerpen)',
    nextSetup: 'Volgende (instellingen)',
    nextPlayers: 'Volgende (spelers)',
    stepOf: 'Stap {n} van {total}',
    stepLanguages: 'Talen & niveau',
    stepTopics: 'Onderwerpen',
    stepSetup: 'Wedstrijdinstellingen',
    stepPlayers: 'Spelersnamen',
    tapMascot: 'Klaar voor feest! Tik me!',
    onlineMultiplayer: 'Online (Discord / Meet)',
    installApp: 'Installeer op je telefoon',
    installSub: 'Op beginscherm • Offline',
    addToHome: 'Installeren',
    comingSoonStores: 'Android- en iOS-apps komen eraan',
    essentialsTopics: 'Essentieel',
    activeCount: '{n} talen',
    hearPhrase: 'Luister',
    tagline: 'Geef de telefoon door. Versla de klok. Spreek.',
    startNewGame: 'Nieuw Spel',
    singlePlayerBtn: 'Singleplayer',
    onlineRoom: 'Online kamer',
    gameHistory: 'Spelgeschiedenis',
    gameRules: 'Spelregels & Handleiding',
    profileLeaderboard: 'Profiel & Ranglijst',
    changeLanguage: 'App-taal wijzigen',
    vocabParty: 'WOORDENSCHAT & PARTY-SPEL',
    multiLingual: 'Meertalig',
    matchSettingsSubtitle: 'Wedstrijdinstellingen, talen & regels',
    playersAndRounds: 'Spelers & Rondes',
    totalPlayersLabel: 'Totaal spelers (2 per team):',
    teams: 'Teams',
    team: 'Team',
    playerNamesAndTeams: 'Spelersnamen & Teams:',
    randomize: 'Willekeurig 🎲',
    targetLanguages: 'Doeltalen (Leren)',
    targetLanguagesSub: 'Kaarten testen woorden in deze talen',
    searchLanguagePlaceholder: 'Zoek taal om toe te voegen...',
    all38Languages: 'Alle 38 ▾',
    removeLanguage: 'Taal verwijderen',
    added: 'Toegevoegd ✓',
    add: '+ Toevoegen',
    cefrLevel: 'Moeilijkheidsgraad (CEFR)',
    nativeLanguage: 'Moedertaal / hulptaal',
    changeNative: 'Wijzigen ▾',
    appUiLanguage: 'Interface-taal',
    changeUi: 'Wijzig ▾',
    tableSeatingTitle: 'Tafelopstelling',
    tableSeatingTip: 'Teamgenoten zitten recht tegenover elkaar! Met de klok mee.',
    seatedStart: 'We zitten! Start ronde 1',
    describeFor: 'Omschrijf dit woord voor {player}:',
    activeTurn: 'Aan de beurt:',
    guessedCorrectly: 'Goed geraden! (+pt)',
    passWrong: 'Pas / Fout',
    audioPronunciation: 'Uitspraak beluisteren',
    timeAdded: '⏱️ +10s tijd toegevoegd!',
    hintActivated: '💡 Hint geactiveerd!',
    almostCorrect: 'Bijna goed (Stem)',
    listeningTeammates: '🎙️ Luisteren naar teamgenoten...',
    yourTurnToGuess: '🙈 Jij bent aan de beurt om te raden!',
    cardHiddenGuesser: 'De kaart is verborgen op je scherm. Luister naar je teamgenoten in het gesprek en raad het woord!',
    championTeam: 'Kampioensteam:',
    matchComplete: 'Wedstrijd voltooid! 🏆',
    shareScorecard: 'Deel scorekaart 📤',
    exitToMenu: 'Terug naar hoofdmenu',
    react: 'Reageer:',
    roomCode: 'Kamercode:',
    freeVoice: 'Gratis spraak',
    joinCall: 'Deelnemen aan gesprek',
    waitingHost: 'Wachten op host om te starten...',
    copied: 'Gekopieerd',
    copy: 'Kopiëren',
    directLink: 'Link',
    connectedPlayersCount: 'Verbonden spelers ({n}):',
    clickToSwitchTeam: 'Klik op een team om te wisselen',
    noPlayers: 'Geen spelers',
    youBadge: 'Jij',
    joinTeam: 'Meedoen',
    roundDurationLabel: 'Rondeduur:',
    secondsUnit: 'seconden',
    enterRoomCode: 'Voer 5-letterige code in:',
    joinGameBtn: 'Kamer betreden',
    createRoomBtn: 'Nieuwe online kamer maken',
    close: 'Sluiten',
    refresh: 'Vernieuwen',
    fastOffline: 'Snel, schermvullend & offline',
    installDirect: '1-klik installatie',
    worksOffline: 'Werkt 100% offline',
    toggleTableSeating: 'Tafelopstelling tonen/verbergen',
    gameSettings: 'Spelinstellingen',
    searchLanguages: 'Zoek talen... (bijv. Nederlands, English, de)',
    myNativeLanguage: 'Mijn moedertaal:',
    languagesIWantToLearn: 'Talen die ik wil leren:',
    activeTargetsCount: '{n} actief',
    noLanguagesFound: 'Geen talen gevonden',
    atLeastOneLanguage: 'Minstens één leertaal moet geselecteerd blijven. Oplossing: Tik op een andere taal.',
    howManyPlayers: 'Hoeveel spelers?',
    playersCount: '{n} spelers',
    roundsCountLabel: 'Aantal rondes',
    turnTimeLabel: 'Tijd per beurt',
    autoPronounce: 'Automatische uitspraak',
    autoPronounceDesc: 'Woord wordt voorgelezen zodra de kaart verschijnt',
    hotSeat: 'Hete stoel',
    hotSeatDesc: 'Telefoon snel doorgeven tussen spelers',
    cardDirection: 'Vertaalrichting van kaarten',
    dirNativeToTarget: 'Moedertaal → Doeltaal',
    dirTargetToNative: 'Doeltaal → Moedertaal',
    dirBoth: 'Beide',
    nextStartGame: 'Volgende: Spel starten',
    guideTitle: 'Handleiding',
    guideText1: 'Kies je moedertaal en de talen die je wilt leren. Je kunt meerdere talen tegelijk kiezen.',
    guideText2: 'Draai de cijfersloten omhoog en omlaag om het aantal rondes en de tijd per beurt aan te passen.',
    gotIt: 'Begrepen',
    soundActive: 'Geluid aan',
    soundMuted: 'Geluid uit'
  },

  tr: {
    uiLanguageLabel: 'Uygulama dili',
    uiLanguageHint: 'Sadece düğmeler ve yardım. Kart dilleri ayrı.',
    nativeLanguageHint: 'Kart anlamı bu dilde görünür.',
    nextTopics: 'İleri (konular)',
    nextSetup: 'İleri (ayarlar)',
    nextPlayers: 'İleri (oyuncular)',
    stepOf: 'Adım {n} / {total}',
    stepLanguages: 'Diller ve seviye',
    stepTopics: 'Konular',
    stepSetup: 'Ayarlar',
    stepPlayers: 'Oyuncu adları',
    tapMascot: 'Partiye hazır! Dokun',
    onlineMultiplayer: 'Çevrimiçi (Discord / Meet)',
    installApp: 'Telefona yükle',
    installSub: 'Ana ekran • Çevrimdışı',
    addToHome: 'Yükle',
    comingSoonStores: 'Android ve iOS yakında',
    essentialsTopics: 'Temel konular',
    activeCount: '{n} dil',
    hearPhrase: 'Dinle',
    tagline: 'Telefonu elden ele geçir. Zamanı yen. Konuş.',
    startNewGame: 'Yeni Oyun',
    singlePlayerBtn: 'Tek oyunculu',
    onlineRoom: 'Çevrimiçi oda',
    gameHistory: 'Oyun geçmişi',
    gameRules: 'Oyun kuralları ve rehber',
    profileLeaderboard: 'Profil ve liderlik tablosu',
    changeLanguage: 'Uygulama dilini değiştir',
    vocabParty: 'KELİME VE DİL PARTİSİ',
    multiLingual: 'Çok Dilli',
    matchSettingsSubtitle: 'Maç ayarları, diller ve kurallar',
    playersAndRounds: 'Oyuncular ve Raundlar',
    totalPlayersLabel: 'Toplam oyuncu (Takım başına 2):',
    teams: 'Takım',
    team: 'Takım',
    playerNamesAndTeams: 'Oyuncu isimleri ve takımlar:',
    randomize: 'Rastgele 🎲',
    targetLanguages: 'Hedef diller (Öğrenme)',
    targetLanguagesSub: 'Kartlar bu dillerdeki kelimeleri sorar',
    searchLanguagePlaceholder: 'Etiketlemek için dil ara...',
    all38Languages: 'Tüm 38 ▾',
    removeLanguage: 'Dili kaldır',
    added: 'Eklendi ✓',
    add: '+ Ekle',
    cefrLevel: 'Zorluk seviyesi (CEFR)',
    nativeLanguage: 'Ana dil / destek dili',
    changeNative: 'Değiştir ▾',
    appUiLanguage: 'Uygulama arayüz dili',
    changeUi: 'Değiştir ▾',
    tableSeatingTitle: 'Masa düzeni rehberi',
    tableSeatingTip: 'Takım arkadaşları birbirinin tam karşısına oturur! Sıra saat yönünde ilerler.',
    seatedStart: 'Oturanlar hazır! 1. Raundu başlat',
    describeFor: 'Bu kelimeyi {player} için anlat:',
    activeTurn: 'Tahmin sırası:',
    guessedCorrectly: 'Doğru tahmin! (+puan)',
    passWrong: 'Pas / Yanlış',
    audioPronunciation: 'Telaffuzu dinle',
    timeAdded: '⏱️ +10sn süre eklendi!',
    hintActivated: '💡 İpucu aktifleştirildi!',
    almostCorrect: 'Neredeyse doğru (Oylama)',
    listeningTeammates: '🎙️ Takım arkadaşlarını dinliyor...',
    yourTurnToGuess: '🙈 Tahmin etme sırası sende!',
    cardHiddenGuesser: 'Kartın ipucu vermemesi için ekranında gizlendi. Sesli aramada arkadaşlarını dinle ve hedef kelimeyi tahmin et!',
    championTeam: 'Şampiyon Takım:',
    matchComplete: 'Maç tamamlandı! 🏆',
    shareScorecard: 'Sonuç karnesini paylaş 📤',
    exitToMenu: 'Ana menüye dön',
    react: 'Tepki ver:',
    roomCode: 'Oda kodu:',
    freeVoice: 'Ücretsiz ses',
    joinCall: 'Aramaya katıl',
    waitingHost: 'Oyun kurucunun başlatması bekleniyor...',
    copied: 'Kopyalandı',
    copy: 'Kopyala',
    directLink: 'Bağlantı',
    connectedPlayersCount: 'Bağlı oyuncular ({n}):',
    clickToSwitchTeam: 'Geçiş yapmak için takıma tıkla',
    noPlayers: 'Oyuncu yok',
    youBadge: 'Ben',
    joinTeam: 'Katıl',
    roundDurationLabel: 'Raund süresi:',
    secondsUnit: 'saniye',
    enterRoomCode: '5 haneli oda kodunu girin:',
    joinGameBtn: 'Odaya katıl',
    createRoomBtn: 'Yeni çevrimiçi oda kur',
    close: 'Kapat',
    refresh: 'Yenile',
    fastOffline: 'Hızlı, tam ekran ve çevrimdışı',
    installDirect: 'Tek tıkla kurulum',
    worksOffline: '%100 çevrimdışı çalışır',
    toggleTableSeating: 'Masa düzenini göster/gizle'
  },

  ar: {
    uiLanguageLabel: 'لغة التطبيق',
    uiLanguageHint: 'الأزرار والمساعدة فقط. لغات البطاقات منفصلة.',
    nativeLanguageHint: 'معنى البطاقة يظهر بهذه اللغة.',
    nextTopics: 'التالي (المواضيع)',
    nextSetup: 'التالي (الإعدادات)',
    nextPlayers: 'التالي (اللاعبون)',
    stepOf: 'الخطوة {n} من {total}',
    stepLanguages: 'اللغات والمستوى',
    stepTopics: 'المواضيع',
    stepSetup: 'إعدادات المباراة',
    stepPlayers: 'أسماء اللاعبين',
    tapMascot: 'جاهز للحفل! اضغطني',
    onlineMultiplayer: 'لعب عبر الإنترنت (ديسكورد / ميت)',
    installApp: 'تثبيت على الجوال',
    installSub: 'الشاشة الرئيسية • دون إنترنت',
    addToHome: 'تثبيت',
    comingSoonStores: 'تطبيقات أندرويد وiOS قريبًا',
    essentialsTopics: 'الأساسيات',
    activeCount: '{n} لغات',
    hearPhrase: 'استمع',
    tagline: 'مرر الهاتف. اهزم الوقت. تحدث.',
    startNewGame: 'بدء لعبة جديدة',
    singlePlayerBtn: 'لاعب فردي',
    onlineRoom: 'غرفة أونلاين',
    gameHistory: 'سجل المباريات',
    gameRules: 'دليل وقواعد اللعبة',
    profileLeaderboard: 'الملف ولوحة المتصدرين',
    changeLanguage: 'تغيير لغة التطبيق',
    vocabParty: 'تحدي المفردات والمحادثة الجماعية',
    multiLingual: 'متعدد اللغات',
    matchSettingsSubtitle: 'إعدادات المباراة واللغات والقواعد',
    playersAndRounds: 'اللاعبون وجولات المباراة',
    totalPlayersLabel: 'إجمالي اللاعبين (لاعبان في كل فريق):',
    teams: 'فرق',
    team: 'فريق',
    playerNamesAndTeams: 'أسماء اللاعبين والفرق:',
    randomize: 'عشوائي 🎲',
    targetLanguages: 'لغات الهدف (قيد التعلم)',
    targetLanguagesSub: 'ستختبر البطاقات الكلمات بهذه اللغات',
    searchLanguagePlaceholder: 'ابحث عن لغة لإضافتها...',
    all38Languages: 'كل الـ 38 ▾',
    removeLanguage: 'إزالة هذه اللغة',
    added: 'تمت الإضافة ✓',
    add: '+ إضافة',
    cefrLevel: 'مستوى الصعوبة والإتقان (CEFR)',
    nativeLanguage: 'اللغة الأم ودليل البطاقات',
    changeNative: 'تغيير ▾',
    appUiLanguage: 'لغة واجهة التطبيق',
    changeUi: 'تغيير الواجهة ▾',
    tableSeatingTitle: 'ترتيب الجلوس حول الطاولة',
    tableSeatingTip: 'يجلس أعضاء الفريق مقابل بعضهم تمامًا! تدور الأدوار مع عقارب الساعة.',
    seatedStart: 'جلسنا! ابدأ الجولة 1',
    describeFor: 'صف هذه الكلمة لـ {player}:',
    activeTurn: 'دور الشرح والتخمين:',
    guessedCorrectly: 'تخمين صحيح! (+نقاط)',
    passWrong: 'تمرير / خطأ',
    audioPronunciation: 'تشغيل النطق الصوتي',
    timeAdded: '⏱️ تم إضافة 10 ثوانٍ!',
    hintActivated: '💡 تم تفعيل التلميح!',
    almostCorrect: 'شبه صحيح (تصويت)',
    listeningTeammates: '🎙️ استمع إلى زملائك في الفريق...',
    yourTurnToGuess: '🙈 حان دورك للتخمين!',
    cardHiddenGuesser: 'البطاقة مخفية على شاشتك لتجنب حرق الكلمة. استمع لزملائك في المكالمة الصوتية وخمن الكلمة المطلوبة!',
    championTeam: 'الفريق البطل:',
    matchComplete: 'انتهت المباراة! 🏆',
    shareScorecard: 'مشاركة بطاقة النتائج 📤',
    exitToMenu: 'العودة إلى القائمة الرئيسية',
    react: 'رد الفعل:',
    roomCode: 'رمز الغرفة:',
    freeVoice: 'محادثة صوتية مجانية',
    joinCall: 'الانضمام للمكالمة',
    waitingHost: 'في انتظار المضيف لبدء اللعبة...',
    copied: 'تم النسخ',
    copy: 'نسخ الرمز',
    directLink: 'رابط مباشر',
    connectedPlayersCount: 'اللاعبون المتصلون ({n}):',
    clickToSwitchTeam: 'اضغط على الفريق للتبديل',
    noPlayers: 'لا يوجد لاعبون',
    youBadge: 'أنا',
    joinTeam: 'انضمام',
    roundDurationLabel: 'مدة الجولة:',
    secondsUnit: 'ثوانٍ',
    enterRoomCode: 'أدخل رمز الغرفة المكون من 5 أحرف:',
    joinGameBtn: 'دخول الغرفة',
    createRoomBtn: 'إنشاء غرفة جديدة',
    close: 'إغلاق',
    refresh: 'تحديث',
    fastOffline: 'سريع، ملء الشاشة ودون إنترنت',
    installDirect: 'تثبيت بنقرة واحدة',
    worksOffline: 'يعمل 100% دون إنترنت',
    toggleTableSeating: 'إظهار / إخفاء ترتيب الطاولة'
  },

  ru: {
    uiLanguageLabel: 'Язык приложения',
    uiLanguageHint: 'Только кнопки и подсказки. Языки карточек настраиваются отдельно.',
    nativeLanguageHint: 'Значения карточек будут на этом языке.',
    nextTopics: 'Далее (темы)',
    nextSetup: 'Далее (настройки)',
    nextPlayers: 'Далее (игроки)',
    stepOf: 'Шаг {n} из {total}',
    stepLanguages: 'Языки и уровень',
    stepTopics: 'Темы',
    stepSetup: 'Настройки матча',
    stepPlayers: 'Имена игроков',
    tapMascot: 'Готовы к вечеринке! Нажми',
    onlineMultiplayer: 'Онлайн игра (Discord / Meet)',
    installApp: 'Установить на телефон',
    installSub: 'На главный экран • Офлайн',
    addToHome: 'Установить',
    comingSoonStores: 'Приложения Android и iOS скоро появятся',
    essentialsTopics: 'Основные темы',
    activeCount: '{n} яз.',
    hearPhrase: 'Слушать',
    tagline: 'Передавай телефон. Обгони время. Говори.',
    startNewGame: 'Новая игра',
    singlePlayerBtn: 'Один игрок',
    onlineRoom: 'Онлайн комната',
    gameHistory: 'История игр',
    gameRules: 'Правила и руководство',
    profileLeaderboard: 'Профиль и таблица лидеров',
    changeLanguage: 'Изменить язык приложения',
    vocabParty: 'КОМАНДНАЯ ИГРА СЛОВ И ОБЩЕНИЯ',
    multiLingual: 'Многоязычный',
    matchSettingsSubtitle: 'Настройки матча, языки и правила',
    playersAndRounds: 'Игроки и раунды матча',
    totalPlayersLabel: 'Всего игроков (по 2 в команде):',
    teams: 'Команды',
    team: 'Команда',
    playerNamesAndTeams: 'Имена игроков и команды:',
    randomize: 'Случайно 🎲',
    targetLanguages: 'Целевые языки (Изучаемые)',
    targetLanguagesSub: 'Карточки будут проверять слова на этих языках',
    searchLanguagePlaceholder: 'Поиск языка для добавления...',
    all38Languages: 'Все 38 ▾',
    removeLanguage: 'Удалить этот язык',
    added: 'Добавлено ✓',
    add: '+ Добавить',
    cefrLevel: 'Уровень сложности (CEFR)',
    nativeLanguage: 'Родной язык / подсказки',
    changeNative: 'Изменить ▾',
    appUiLanguage: 'Язык интерфейса приложения',
    changeUi: 'Изменить ▾',
    tableSeatingTitle: 'Рассадка вокруг стола',
    tableSeatingTip: 'Партнеры по команде сидят друг напротив друга! Ход по часовой стрелке.',
    seatedStart: 'Мы расселись! Начать 1-й раунд',
    describeFor: 'Опишите это слово для {player}:',
    activeTurn: 'Очередь угадывать:',
    guessedCorrectly: 'Правильно! (+очки)',
    passWrong: 'Пас / Ошибка',
    audioPronunciation: 'Прослушать произношение',
    timeAdded: '⏱️ +10 секунд добавлено!',
    hintActivated: '💡 Подсказка активирована!',
    almostCorrect: 'Почти правильно (Голосование)',
    listeningTeammates: '🎙️ Слушаем товарищей по команде...',
    yourTurnToGuess: '🙈 Ваша очередь угадывать!',
    cardHiddenGuesser: 'Карточка скрыта на вашем экране, чтобы не раскрывать слово. Слушайте товарищей в голосовом чате и угадывайте!',
    championTeam: 'Команда-победитель:',
    matchComplete: 'Матч завершен! 🏆',
    shareScorecard: 'Поделиться результатом 📤',
    exitToMenu: 'В главное меню',
    react: 'Реакция:',
    roomCode: 'Код комнаты:',
    freeVoice: 'Бесплатный звук',
    joinCall: 'Войти в звонок',
    waitingHost: 'Ожидание ведущего для запуска игры...',
    copied: 'Скопировано',
    copy: 'Копировать',
    directLink: 'Ссылка',
    connectedPlayersCount: 'Подключено игроков ({n}):',
    clickToSwitchTeam: 'Нажмите на команду для перехода',
    noPlayers: 'Нет игроков',
    youBadge: 'Вы',
    joinTeam: 'Войти',
    roundDurationLabel: 'Длительность раунда:',
    secondsUnit: 'секунд',
    enterRoomCode: 'Введите 5-значный код комнаты:',
    joinGameBtn: 'Войти в комнату',
    createRoomBtn: 'Создать новую комнату',
    close: 'Закрыть',
    refresh: 'Обновить',
    fastOffline: 'Быстро, полноэкранно и офлайн',
    installDirect: 'Установка в 1 клик',
    worksOffline: 'Работает 100% без интернета',
    toggleTableSeating: 'Показать / скрыть рассадку'
  }
};

export function tUI(lang: Language | string): any {
  const code = resolveUiLang(lang as Language);
  const base = TRANSLATIONS[code] || TRANSLATIONS.en || {};
  const extra = UI_STRINGS[code] || {};

  // Smart derivation: bridge any missing key from base to extra so standard terms are localized
  const derived: Record<string, any> = {};
  if (!extra.startNewGame && (base.newGame || base.start)) derived.startNewGame = base.newGame || base.start;
  if (!extra.setup && base.setup) derived.setup = base.setup;
  if (!extra.guide && (base.guide || base.rules)) derived.guide = base.guide || base.rules;
  if (!extra.history && base.history) derived.history = base.history;
  if (!extra.players && base.players) derived.players = base.players;
  if (!extra.rounds && base.rounds) derived.rounds = base.rounds;
  if (!extra.team && base.team) derived.team = base.team;
  if (!extra.teams && (base.teams || base.team)) derived.teams = base.teams || base.team;
  if (!extra.close && base.exit) derived.close = base.exit;
  if (!extra.winner && base.winner) derived.winner = base.winner;
  if (!extra.round && base.round) derived.round = base.round;
  if (!extra.score && (base.totalScore || base.score)) derived.score = base.totalScore || base.score;
  if (!extra.accuracy && base.accuracyLabel) derived.accuracy = base.accuracyLabel;
  if (!extra.playAgain && base.playAgain) derived.playAgain = base.playAgain;
  if (!extra.returnMenu && base.returnMenu) derived.returnMenu = base.returnMenu;
  if (!extra.vocabParty && base.subtitle) derived.vocabParty = base.subtitle;
  if (!extra.tagline && base.subtitle) derived.tagline = base.subtitle;
  if (!extra.singlePlayerBtn && base.singlePlayer) derived.singlePlayerBtn = base.singlePlayer;
  if (!extra.onlineRoom && base.onlineRoom) derived.onlineRoom = base.onlineRoom;

  return {
    ...TRANSLATIONS.en,
    ...UI_STRINGS.en,
    ...base,
    ...derived,
    ...extra
  };
}

export function toPersianDigits(str: string | number): string {
  const persianDigits = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
  return String(str).replace(/[0-9]/g, (w) => persianDigits[+w]);
}

export function tf(lang: Language | string, key: string, vars?: Record<string, string | number>): string {
  const pack = tUI(lang);
  let s = (pack[key] as string) || (UI_STRINGS.en && UI_STRINGS.en[key]) || key;
  if (vars) {
    s = s.replace(/\{(\w+)\}/g, (_, k) => {
      const val = vars[k] ?? '';
      if (lang === 'fa' && (typeof val === 'number' || /^\d+$/.test(String(val)))) {
        return toPersianDigits(val);
      }
      return String(val);
    });
  }
  return s;
}

export function getTeamName(colorOrIndex: string | number, lang: Language | string): string {
  const pack = tUI(lang);
  const colorMap: Record<string, string> = pack.teamNames || {
    BLUE: 'Blue',
    RED: 'Red',
    GREEN: 'Green',
    YELLOW: 'Yellow'
  };
  const teamWord = pack.team || 'Team';
  
  if (typeof colorOrIndex === 'number') {
    const colors = ['BLUE', 'RED', 'GREEN', 'YELLOW'];
    const c = colors[colorOrIndex % colors.length];
    const localizedColor = colorMap[c] || c;
    return `${teamWord} ${localizedColor}`;
  }
  
  const c = String(colorOrIndex).toUpperCase();
  const localizedColor = colorMap[c] || c;
  return `${teamWord} ${localizedColor}`;
}
