plugins {
    id 'com.android.application'
}

android {
    namespace 'com.solonovate.dour'
    compileSdk 36

    defaultConfig {
        applicationId "com.solonovate.dour"
        minSdk 21
        targetSdk 36
        versionCode 10003
        versionName "1.0.3"
    }

    signingConfigs {
        release {
            storeFile file('../release.keystore')
            storePassword 'dorzaban2026'
            keyAlias 'dor-release'
            keyPassword 'dorzaban2026'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.10.0'
}
